package com.medimind.backend;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.util.Optional;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    // Automatically generated by Spring Data JPA:
    // - save(user)
    // - findById(id)
    // - delete(user)
    // - findAll()

    // Custom method: Find user by email
    Optional<User> findByEmail(String email);
}